
import copy


def generate_payload(bookings):
    # Extract relevant fields from both bookings
    booking_0 = bookings[0]
    booking_1 = bookings[1]
    # Common structure for the new booking
    payload = {
        "booking": {
            "bookingType": booking_0["bookingType"],
            "bookingTitle": booking_0["bookingTitle"],
            "bookedResourceName": booking_0["bookedResourceName"],
            "bookedResourceItemId": booking_0["bookedResourceItemId"],
            "floor": booking_0["floor"],
            "bookedLocation": booking_0["bookedLocation"],
            "bookingId": booking_0["bookingId"],
            "bookingItemId": booking_0["bookingItemId"],
            "bookedBy": booking_0["bookedBy"],
            "requestedBy": None,
            "bookedFor": None,
            "startDateTime": booking_0["startDateTime"],
            "endDateTime": booking_0["endDateTime"],
            "startDateTimeUtc": booking_0["startDateTimeUtc"],
            "endDateTimeUtc": booking_0["endDateTimeUtc"],
            "bookingStatus": 0,
            "businessUnitId": 133,
            "locationId": 12,
            "locationTimeZone": "E. Australia Standard Time",
            "parentBookingId": None,
            "vcId": None,
            "approved": False,
            "pendingOnGrid": False,
            "waitList": False,
            "blindManaged": False,
            "managedForAdmin": False,
            "resourceStatus": 0,
            "encryptedQuerstringReviewSummary": None,
            "amReleased": None,
            "pmReleased": None,
            "fdCheckedIn": None,
            "fdReleased": None,
            "bookingMetadata": {
                "attendees": None,
                "rules": booking_0["bookingMetadata"]["rules"],  # Use same rules from booking 0 MAY NEED TO EDIT
                "isCurrentUserMeetingAdmin": False
            },
            "minutesToExtend": None,
            "updateDateTime": None,
            "updateDateTimeUtc": None,
            "bookingSource": 0,
            "enterpriseBookingSource": 0,
            "individuallyEdited": False,
            "timeZoneId": booking_0["timeZoneId"],
            "changedByUserId": 0,
            "enableSelfCertificationOnLocation": False,
            "selfCertificationContent": "",
            "selfCertificationDisagreeContent": "",
            "enableDeskCheckinLocationTimeZone": 1,
            "wsTypeId": 2,
            "qrCodeEnabled": False,
            "disableWebCheckIn": False,
            "assetURL": None,
            "floorName": "",
            "isWorkplace": None,
            "recurrenceID": 0,
            "languageId": 0,
            "floorPlanOnMap": True,
            "preventSpecificSpaceRequests": False,
            "enableMeetingSpacesFloorPlan": True,
            "isAllDayBooking": True,
            "otherSameDayBookings": [
                {
                    "bookingType": booking_1["bookingType"],
                    "bookingTitle": booking_1["bookingTitle"],
                    "bookedResourceName": booking_1["bookedResourceName"],
                    "bookedResourceItemId": booking_1["bookedResourceItemId"],
                    "floor": booking_1["floor"],
                    "bookedLocation": booking_1["bookedLocation"],
                    "bookingId": booking_1["bookingId"],
                    "bookingItemId": booking_1["bookingItemId"],
                    "bookedBy": booking_1["bookedBy"],
                    "requestedBy": None,
                    "bookedFor": None,
                    "startDateTime": booking_1["startDateTime"],
                    "endDateTime": booking_1["endDateTime"],
                    "startDateTimeUtc": booking_1["startDateTimeUtc"],
                    "endDateTimeUtc": booking_1["endDateTimeUtc"],
                    "bookingStatus": 3,
                    "businessUnitId": 133,
                    "locationId": 12,
                    "locationTimeZone": "E. Australia Standard Time",
                    "parentBookingId": None,
                    "vcId": None,
                    "approved": False,
                    "pendingOnGrid": False,
                    "waitList": False,
                    "blindManaged": False,
                    "managedForAdmin": False,
                    "resourceStatus": 0,
                    "encryptedQuerstringReviewSummary": None,
                    "amReleased": None,
                    "pmReleased": None,
                    "fdCheckedIn": None,
                    "fdReleased": None,
                    "bookingMetadata": {
                        "attendees": None,
                        "rules": booking_1["bookingMetadata"]["rules"],  # Use rules from booking 1
                        "isCurrentUserMeetingAdmin": False
                    },
                    "minutesToExtend": None,
                    "updateDateTime": None,
                    "updateDateTimeUtc": None,
                    "bookingSource": 0,
                    "enterpriseBookingSource": 0,
                    "individuallyEdited": False,
                    "timeZoneId": booking_1["timeZoneId"],
                    "changedByUserId": 0,
                    "enableSelfCertificationOnLocation": False,
                    "selfCertificationContent": "",
                    "selfCertificationDisagreeContent": "",
                    "enableDeskCheckinLocationTimeZone": 1,
                    "wsTypeId": 2,
                    "qrCodeEnabled": False,
                    "disableWebCheckIn": False,
                    "assetURL": None,
                    "floorName": "",
                    "isWorkplace": None,
                    "recurrenceID": 0,
                    "languageId": 0,
                    "floorPlanOnMap": True,
                    "preventSpecificSpaceRequests": False,
                    "enableMeetingSpacesFloorPlan": True,
                    "IsAllowedWithinCancelBeforeLimit": True,
                    "hasValidNoticeForExtend": True
                }
            ],
            "disableWebCheckIn": False,
            "bookingMetadata": {
                "attendees": None,
                "rules": booking_0["bookingMetadata"]["rules"],  # Use rules from booking 0
                "isCurrentUserMeetingAdmin": False
            },
            "IsAllowedWithinCancelBeforeLimit": False,
            "hasValidNoticeForExtend": True
        },
        "fetchingExtend": False,
        "showExtend": False,
        "avalibility": None,
        "availableTimeSlots": [],
        "showBookingStart": False,
        "showBookingStartDisabled": False,
        "showDeleteActionDisabled": False,
        "showBooking": True,
        "otherSameDayBookings": [
            {
                "bookingType": booking_1["bookingType"],
                "bookingTitle": booking_1["bookingTitle"],
                "bookedResourceName": booking_1["bookedResourceName"],
                "bookedResourceItemId": booking_1["bookedResourceItemId"],
                "floor": booking_1["floor"],
                "bookedLocation": booking_1["bookedLocation"],
                "bookingId": booking_0["bookingId"],
                "bookingItemId": booking_0["bookingItemId"],
                "bookedBy": booking_1["bookedBy"],
                "requestedBy": None,
                "bookedFor": None,
                "startDateTime": booking_1["startDateTime"],
                "startDateTimeUtc": booking_1["startDateTimeUtc"],
                "endDateTime": booking_1["endDateTime"],
                "endDateTimeUtc": booking_1["endDateTimeUtc"],
                "bookingStatus": 3,
                "businessUnitId": 133,
                "locationId": 12,
                "locationTimeZone": "E. Australia Standard Time",
                "parentBookingId": None,
                "vcId": None,
                "approved": False,
                "pendingOnGrid": False,
                "waitList": False,
                "blindManaged": False,
                "managedForAdmin": False,
                "resourceStatus": 0,
                "encryptedQuerstringReviewSummary": None,
                "amReleased": None,
                "pmReleased": None,
                "fdCheckedIn": None,
                "fdReleased": None,
                "bookingMetadata": {
                    "attendees": None,
                    "rules": booking_1["bookingMetadata"]["rules"],  # Use rules from booking 1
                    "isCurrentUserMeetingAdmin": False
                },
                "minutesToExtend": None,
                "updateDateTime": None,
                "updateDateTimeUtc": None,
                "bookingSource": 0,
                "enterpriseBookingSource": 0,
                "individuallyEdited": False,
                "timeZoneId": booking_0["timeZoneId"],
                "changedByUserId": 0,
                "enableSelfCertificationOnLocation": False,
                "selfCertificationContent": "",
                "selfCertificationDisagreeContent": "",
                "enableDeskCheckinLocationTimeZone": 1,
                "wsTypeId": 2,
                "qrCodeEnabled": False,
                "disableWebCheckIn": False,
                "assetURL": None,
                "floorName": "",
                "isWorkplace": None,
                "recurrenceID": 0,
                "languageId": 0,
                "floorPlanOnMap": True,
                "preventSpecificSpaceRequests": False,
                "enableMeetingSpacesFloorPlan": True,
                "IsAllowedWithinCancelBeforeLimit": True,
                "hasValidNoticeForExtend": True
            }
        ],
        "canExtentBooking": True,
        "IsAllowedWithinCancelBeforeLimit": False,
        "hasValidNoticeForExtend": True,
        "disableWebCheckIn": False,
        "bookingMetadata": {
            "attendees": None,
            "rules": booking_1["bookingMetadata"]["rules"],  # Use same rules from booking 0
            "isCurrentUserMeetingAdmin": False
        },
        "startDateTime": booking_1["startDateTime"],
        "startDateTimeUtc": booking_1["startDateTimeUtc"],
        "endDateTime": booking_1["endDateTime"],
        "endDateTimeUtc": booking_1["endDateTimeUtc"],
        "originalBookingStatus": 0,
        "bookingType": booking_1["bookingType"],
        "bookingTitle": booking_1["bookingTitle"],
        "bookedResourceName": booking_1["bookedResourceName"],
        "bookedResourceItemId": booking_1["bookedResourceItemId"],
        "floor": booking_1["floor"],
        "bookedLocation": booking_1["bookedLocation"],
        "bookingId": booking_0["bookingId"],
        "bookingItemId": booking_0["bookingItemId"],
        "bookedBy": booking_1["bookedBy"],
        "requestedBy": None,
        "bookedFor": None,
        "bookingStatus": 1,
        "businessUnitId": 133,
        "locationId": 12,
        "locationTimeZone": "E. Australia Standard Time",
        "parentBookingId": None,
        "vcId": None,
        "approved": False,
        "pendingOnGrid": False,
        "waitList": False,
        "blindManaged": False,
        "managedForAdmin": False,
        "resourceStatus": 0,
        "encryptedQuerstringReviewSummary": None,
        "amReleased": None,
        "pmReleased": None,
        "fdCheckedIn": None,
        "fdReleased": None,
        "minutesToExtend": None,
        "updateDateTime": None,
        "updateDateTimeUtc": None,
        "bookingSource": 0,
        "enterpriseBookingSource": 0,
        "individuallyEdited": False,
        "timeZoneId": booking_0["timeZoneId"],
        "changedByUserId": 0,
        "enableSelfCertificationOnLocation": False,
        "selfCertificationContent": "",
        "selfCertificationDisagreeContent": "",
        "enableDeskCheckinLocationTimeZone": 1,
        "wsTypeId": 2,
        "qrCodeEnabled": False,
        "assetURL": None,
        "floorName": "",
        "isWorkplace": None,
        "recurrenceID": 0,
        "languageId": 0,
        "floorPlanOnMap": True,
        "preventSpecificSpaceRequests": False,
        "enableMeetingSpacesFloorPlan": True,
        "isAllDayBooking": True
    }
    return payload

def generate_secondary_payload(booking):
    payload = {
        "booking": copy.deepcopy(booking),
        "fetchingExtend": False,
        "showExtend": False,
        "avalibility": None,
        "availableTimeSlots": [],
        "showBookingStart": False,
        "showBookingStartDisabled": False,
        "showDeleteActionDisabled": False,
        "showBooking": True,
        "otherSameDayBookings": [],
        "canExtentBooking": True,
        "IsAllowedWithinCancelBeforeLimit": True,
        "hasValidNoticeForExtend": True,
        "disableWebCheckIn": False,
        "bookingMetadata": copy.deepcopy(booking.get("bookingMetadata", {}))
    }
    
    # Updating specific fields
    payload["booking"]["bookingId"] += 2
    payload["booking"]["bookingItemId"] += 4
    payload["booking"]["startDateTime"] = "2025-02-26T12:00:00"
    payload["booking"]["endDateTime"] = "2025-02-26T23:59:00"
    payload["booking"]["startDateTimeUtc"] = "2025-02-26T02:00:00"
    payload["booking"]["endDateTimeUtc"] = "2025-02-26T13:59:00"
    payload["booking"]["bookingStatus"] = 3
    payload["booking"]["IsAllowedWithinCancelBeforeLimit"] = True
    payload["booking"]["hasValidNoticeForExtend"] = True
    
    # Adding additional fields at root level
    for key in [
        "startDateTime", "startDateTimeUtc", "endDateTime", "endDateTimeUtc",
        "bookingType", "bookingTitle", "bookedResourceName", "bookedResourceItemId",
        "floor", "bookedLocation", "bookingId", "bookingItemId", "bookedBy",
        "requestedBy", "bookedFor", "bookingStatus", "businessUnitId", "locationId",
        "locationTimeZone", "parentBookingId", "vcId", "approved", "pendingOnGrid",
        "waitList", "blindManaged", "managedForAdmin", "resourceStatus",
        "encryptedQuerstringReviewSummary", "amReleased", "pmReleased", "fdCheckedIn",
        "fdReleased", "minutesToExtend", "updateDateTime", "updateDateTimeUtc",
        "bookingSource", "enterpriseBookingSource", "individuallyEdited", "timeZoneId",
        "changedByUserId", "enableSelfCertificationOnLocation", "selfCertificationContent",
        "selfCertificationDisagreeContent", "enableDeskCheckinLocationTimeZone",
        "wsTypeId", "qrCodeEnabled", "assetURL", "floorName", "isWorkplace",
        "recurrenceID", "languageId", "floorPlanOnMap", "preventSpecificSpaceRequests",
        "enableMeetingSpacesFloorPlan"
    ]:
        payload[key] = payload["booking"].get(key, None)
    
    return payload